version: '3'
services:
  redis:
    container_name: "redis"
    image: "redis:3.0.6-alpine"
    expose:
      - 6379
    volumes:
      - ./../../../../../../data/redis:/data
  blazegraph:
    build:
      args:
        WHYIS_IMAGE_TAG: ${WHYIS_IMAGE_TAG:-latest}
      context: ../../../..
      dockerfile: docker/image/whyis-blazegraph/Dockerfile
    container_name: "blazegraph"
    image: tetherlessworld/whyis-blazegraph:${WHYIS_IMAGE_TAG:-latest}
    volumes:
      - ./../../../../../../data:/data
